added some direnv stuff - might not be done

diff --git a/bashrc_to_copy_to_home_dir b/bashrc_to_copy_to_home_dir
--- a/bashrc_to_copy_to_home_dir
+++ b/bashrc_to_copy_to_home_dir
@@ -25,9 +25,6 @@ shopt -s checkwinsize
 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
     alias ls='ls --color=auto'
-    #alias dir='dir --color=auto'
-    #alias vdir='vdir --color=auto'
-
     alias grep='grep --color=auto'
     alias fgrep='fgrep --color=auto'
     alias egrep='egrep --color=auto'
@@ -50,16 +47,11 @@ alias ...='cd ../..'
 alias ack=ack-grep
 alias vi=gvim
 alias vir='vi --remote-tab'
-alias fileshare='sudo mount -t cifs //fcfs1.pelco.org/Data /mnt/fcfs1 -o rw,user=jim.anderson'
-alias ub='/home/jima/work/avig/unity/tools/ub'
-# alias vm='ssh mgdh46@10.66.4.226'
-alias oldvm='ssh mgdh46@mgdh46-dev-vm-01.am.mot-solutions.com'
+alias ub='/home/jima/work/unity/tools/ub'
 alias vm='ssh mgdh46@mgdh46-dev-01.am.mot-solutions.com'
-alias azlogin='az login --use-device-code && az acr login --name ciedevelop' 
+alias azlogin='az login --use-device-code && az acr login --name ciedevelop'
 
 function sshc { ssh -i ~/.ssh/camera_rsa root@$1; }
-function logenv { . /home/jima/working/logfiles/venv/bin/activate; export PATH=$PATH:/home/jima/working/logfiles:; }
-function fcbuildv { sshpass -p Pbse:282-1900 ssh omons_team@fcbuild${1}vm.pelco.org; }
 function fcbuild { sshpass -p Pbse:282-1900 ssh omons_team@fcbuild${1}.pelco.org; }
 function dotstat { git status .; }
 function showtool { git difftool $1^ $1; }
@@ -68,37 +60,95 @@ function acki { ack --ignore-dir=build/ $*; }
 function ackd { rm -f dump && ack $* > /tmp/dump && mv /tmp/dump .; }
 function ackdd { rm -f dump && ack $* > /tmp/dump && mv /tmp/dump . && vir dump; }
 
-PATH=$PATH:$HOME/bin:/opt/omtools/bin:/sbin
-export PATH=/home/jima/.local/bin:/home/jima/work/omons/build-tools/build-commands:$PATH
-export PATH="$HOME/.poetry/bin:$PATH"
-
-export PATH
+export PATH=/home/jima/bin:/home/jima/.local/bin:$PATH
 
 # forces editor sessions from git to use gvim!
 export VISUAL="$HOME/bin/vimgit.sh"
 
-# Set up git to use the MSI key
-# export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_msi"
-
-export PYTHONPATH="$HOME/work/avig/origcameracontroller/CameraController:$PYTHONPATH"
-export PYTHONPATH
-# set up env for virtualenv wrapper
-export VIRTUALENV_PYTHON=/usr/bin/python3.8
-export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.8
-export WORKON_HOME=$HOME/.virtualenvs
-export PROJECT_HOME=$HOME/work/python
-if [ -f .local/bin//virtualenvwrapper.sh ]; then
-source .local/bin/virtualenvwrapper.sh
-# source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
-fi
-
 ## pyenv configs
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/bin:$PATH"
-
-if command -v pyenv 1>/dev/null 2>&1; then
-  eval "$(pyenv init -)"
-fi
+# export PYENV_ROOT="$HOME/.pyenv"
+# export PATH="$PYENV_ROOT/bin:$PATH"
+# if command -v pyenv 1>/dev/null 2>&1; then
+  # eval "$(pyenv init -)"
+# fi
 
 source ~/bin/git-completion.bash
+
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+
+# pnpm
+export PNPM_HOME="/home/jima/.local/share/pnpm"
+case ":$PATH:" in
+  *":$PNPM_HOME:"*) ;;
+  *) export PATH="$PNPM_HOME:$PATH" ;;
+esac
+# pnpm end
+
+# direnv functions to give venv and workon commands from:
+# https://treyhunner.com/2024/10/switching-from-virtualenvwrapper-to-direnv-starship-and-uv/
+mkvenv() {
+    local venv_name=${1:-$(basename "$PWD")}
+    local projects_file="$HOME/.projects"
+
+    # Check if .envrc already exists
+    if [ -f .envrc ]; then
+        echo "Error: .envrc already exists" >&2
+        return 1
+    fi
+
+    if grep -Fq ${venv_name} ${projects_file}; then
+        echo "Error: a project named ${venv_name} already exists" >&2
+        return 1
+    fi
+
+    # Create venv
+    if ! python3 -m venv .venv --prompt "$venv_name"; then
+        echo "Error: Failed to create venv" >&2
+        return 1
+    fi
+
+    # Create .envrc
+    echo "layout python" > .envrc
+
+    # Append project name and directory to projects file
+    echo "${venv_name} = ${PWD}" >> $projects_file
+
+    # Allow direnv to immediately activate the virtual environment
+    direnv allow
+}
+
+workon() {
+    local project_name="$1"
+    local projects_file="$HOME/.projects"
+    local project_dir
+    # Check for projects config file
+    if [[ ! -f "$projects_file" ]]; then
+        echo "Error: $projects_file not found" >&2
+        return 1
+    fi
+
+    # Get the project directory for the given project name
+    project_dir=$(grep -E "^$project_name\s*=" "$projects_file" | sed 's/^[^=]*=\s*//')
+
+    # Ensure a project directory was found
+    if [[ -z "$project_dir" ]]; then
+        echo "Error: Project '$project_name' not found in $projects_file" >&2
+        return 1
+    fi
+
+    # Ensure the project directory exists
+    if [[ ! -d "$project_dir" ]]; then
+        echo "Error: Directory $project_dir does not exist" >&2
+        return 1
+    fi
+
+    # Change directories
+    cd "$project_dir"
+}
+
 eval "$(starship init bash)"
+# direnv
+eval "$(direnv hook bash)"
+
